# -------------------------------------------------------------------
# 1. Namespace & ServiceAccount (Bound to a restricted backend IAM Role)
# -------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: romedawg
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: romedawg
  namespace: romedawg
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::131261850621:role/romedawg-role
---
# -------------------------------------------------------------------
# 2. Namespaced SecretStore (Connects ESO to the Cloud API using the SA)
# -------------------------------------------------------------------
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: romedawg-ssm-store
  namespace: romedawg
spec:
  provider:
    aws:
      service: ParameterStore # instead of SecretStore
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: romedawg
---
# -------------------------------------------------------------------
# 3. ExternalSecret (Fetches the secret and creates a native K8s Secret)
# -------------------------------------------------------------------
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romedawg-db-secret
  namespace: romedawg
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: romedawg-ssm-store
    kind: SecretStore
  target:
    name: romedawg-db-credentials  # The resulting Kubernetes Secret object name
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USERNAME         # Key inside the Kubernetes Secret
      remoteRef:
        key: /all/dev/romedawg/postgres_username # Path/Key inside AWS Secrets Manager
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /all/dev/romedawg/postgres_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romedawg-registry
  namespace: romedawg
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: romedawg-ssm-store
    kind: SecretStore
  target:
    name: gitlab-registry  # The resulting Kubernetes Secret object name
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "registry.gitlab.com": {
                "username": "{{ .registry_username }}",
                "password": "{{ .registry_password }}",
                "auth": "{{ printf "%s:%s" .registry_username .registry_password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: registry_username         # Key inside the Kubernetes Secret
      remoteRef:
        key: /dev/argocd/gitlab/username # Path/Key inside AWS Secrets Manager
    - secretKey: registry_password
      remoteRef:
        key: /dev/argocd/gitlab/password
---
# 4. Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: romedawg
  namespace: romedawg
  annotations:
    # This annotation links the service account to the IAM role
    eks.amazonaws.com/role-arn: arn:aws:iam::131261850621:role/romedawg-role
spec:
  replicas: 1
  selector:
    matchLabels:
      app: romedawg
  template:
    metadata:
      labels:
        app: romedawg
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      serviceAccountName: romedawg
      containers:
        - name: app
          image: registry.gitlab.com/romedawg/romedawg.com:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DOMAIN
              value: romedawg.cuqo4j764p9h.us-east-2.rds.amazonaws.com
            - name: POSTGRES_DATABASE
              value: blog_db
          envFrom:
            - secretRef:
                name: romedawg-db-credentials
---
# 5. Kubernetes Service (Target for Ingress)
apiVersion: v1
kind: Service
metadata:
  name: romedawg-service
  namespace: romedawg
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: romedawg
---
# 6. AWS Ingress Resource (Triggers ALB & Target Group Provisioning)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: romedawg-ingress
  namespace: romedawg
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:131261850621:certificate/979cb3be-a5e2-4d97-9de2-e693e88cee72
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
spec:
  ingressClassName: alb
  rules:
    - host: romedawg.dev.internal.gohealth.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: romedawg-service
                port:
                  number: 80