server.port=8080
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# PostgreSQL / H2 DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:blog_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
spring.datasource.username=${POSTGRES_USERNAME:sa}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.application.name=blog-site
blog.data.file=classpath:data/posts.json
spring.web.resources.chain.cache=false
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.cache.cachecontrol.no-cache=true

####################
# Liquibase SETTINGS
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml
logging.level.liquibase = ERROR
