server.port=8080
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://${POSTGRES_DOMAIN}:5432/${POSTGRES_DATABASE:blog_db}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.application.name=blog-site
blog.data.file=classpath:data/posts.json
spring.web.resources.chain.cache=false
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.cache.cachecontrol.no-cache=true

####################
# Liquibase SETTINGS
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml
logging.level.liquibase = ERROR
